## Table of Content

1. **[Introduction to Numpy](#python_numpy)**
2. **[Indexing an Array](#indexing)**
3. **[Slicing an Array](#slicing)**
4. **[Operations on Array](#operations)**
5. **[Arithmetic Functions in Numpy](#arithmetic)**
6. **[Concatenation of Array](#concatenation)**
7. **[Splitting of Array](#splitting)**

<a id="python_numpy"> </a>
### 1. Introduction to Numpy
<table align="left">
    <tr>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>NumPy is a python package that stands for ‘Numerical Python’.<br>
                    Numpy is the core library for scientific computing, which contains a powerful n-dimensional array object. It provides tools for integrating C, C++, etc.<br>
                    It also contains a powerful N-dimensional array object.<br>
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [1]:
# import the numpy package as np
import numpy as np

### Python NumPy Array vs List
We use python numpy array instead of a list because of the below three reasons:
1. Less memory<br>
2. Fast<br>
3. Convenient

**The N-dimensional array**<br>
A simple way to create an array from data or simple python data structures lie=ke a list is to use the array() function.

In [2]:
# Create 2 new lists height and weight
person_height = [5.2,  5.4, 4.4, 4.5, 5.6, 6]
person_weight = [81, 55, 65, 70, 45, 44]

# Create 2 numpy arrays from height and weight
person_height = np.array(person_height)
person_weight = np.array([person_weight])

print(type(person_weight))

<class 'numpy.ndarray'>


<a id="indexing"> </a>
### 2. Indexing an Array

**Indexing in 1 dimension**

Each element in the array can be accessed by passing the positional index of the element.
* Indexing starts from 0

In [5]:
# given array
my_array = np.array([11, 22, 33, 24, 57, 473])

# get the third element
print(my_array[2]) 

33


**Indexing in 2 dimensions**

We can retrieve an element of the 2D array using two indices i and j - i selects the row, and j selects the column:

In [18]:
my_2darray = np.array([[101, 231, 321],
              [412, 512, 622],
              [712, 821, 912]])

print(my_2darray)

# get the element in 3rd row (i) and 2nd column (j)
print(my_2darray[2, 1])

[[101 231 321]
 [412 512 622]
 [712 821 912]]
821


We can also select a single row or column.

In [20]:
# pick the third ROW from the array
print(my_2darray[2])

# pick the second COLUMN from the array
print(my_2darray[:,2])

[712 821 912]
[321 622 912]


<a id="Slicing"></a>
### 3. Slicing

**Slicing a 1D array**

The slice notation specifies a start and end value [start:end], where 'start' is inclusive but 'end' is exclusive.

In [21]:
my_array = [101, 121, 112, 123, 114]
print(my_array)

# pick the second, third, and fourth element from the array 
new_array = my_array[1:4]  
print(new_array)

# first three elements
c = my_array[:3]
print(c)

# all the elements from element 112 forward
d = my_array[2:]    
print(d)

# get all the elements from start to end of array
e = my_array[:]
print(e)

[101, 121, 112, 123, 114]
[121, 112, 123]
[101, 121, 112]
[112, 123, 114]
[101, 121, 112, 123, 114]


**Slicing a 2D array**

In [24]:
my_2darray = np.array([[101, 131, 122, 113, 143],
               [145, 165, 137, 318, 193],
               [240, 241, 252, 253, 324],
               [225, 126, 727, 928, 129]])

print(my_2darray)

# select All rows except the 1st row
# select 3rd and 4th column
print(my_2darray[1:, 2:4])

[[101 131 122 113 143]
 [145 165 137 318 193]
 [240 241 252 253 324]
 [225 126 727 928 129]]
[[137 318]
 [252 253]
 [727 928]]


**Note:** The index returns an element of the array, the slice returns a list of elements.

<a id="operations"> </a>
### 4. Operations on Arrays

In [26]:
my_array1 = np.array([120, 230, 310, 410, 150])
my_array2 = np.arange(5)

print(my_array1)
print(my_array2)

[120 230 310 410 150]
[0 1 2 3 4]


In [27]:
# Adding the two arrays
my_array3 = my_array1 + my_array2
my_array3

array([120, 231, 312, 413, 154])

In [29]:
# Sum 2 arrays with different number of elements
my_array4 = np.array([1,2,3,5])
my_array1 + my_array4

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

<table align="left">
    <tr>
        <td>
            <div align="left">
                <font color="#21618C">
                    <b>If you try to add arrays with the same dimension but a different number of elements, you get an error.
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Multiplication and Square**
Use ' ** ' to compute power of the numbers.

In [32]:
# multiply each element in the array by 4 
print(my_array1*4)

# get square of each element
print(my_array1**2)

[ 480  920 1240 1640  600]
[ 14400  52900  96100 168100  22500]


**Using Numpy with Comparison Expressions**

In [34]:
my_array = np.array([34, 45, 67, 45, 23])

# check which elements are greater than or equal to 40
# the comparison condition gives boolean output
new_array = my_array >= 40
new_array

array([False,  True,  True,  True, False])

Pass the above boolean array to the main array to fetch the values that satisfy the comparison condition.

In [36]:
# elements greater than or equal to 40
print(my_array[new_array])

# Rather than creating a separate array of booleans, 
# you can specify the comparison operation directly on the main array.
print(my_array[my_array >= 40])

[45 67 45]
[45 67 45]


<a id="arithmetic"> </a>
### 5. Arithmetic Functions in Numpy

**sum():**<br>
sum() function adds all the values in the array and gives a scalar output.

**min():**<br>
min function finds the lowest value in the array.

**power():**<br>
power function raises the numbers in the array to the given value.

In [38]:
# given array
my_array = np.array([5,7,8,2,4])
my_array

# add all the elements of 'my_array'
print(my_array.sum())

# find minimum of 'my_array'
print(my_array.min())

# get cube of elements of 'my_array'
np.power(my_array, 3)

26
2


array([125, 343, 512,   8,  64])

<a id="concatenation"> </a>
### 6. Concatenation of Array

The arrays can be concatenated only if they have same shape, except in the dimension corresponding to the axis of concatenation.

**Concatenate 1D array**

In [40]:
# concatenate two 1D arrays
array_x = np.array([11, 22, 13])
array_y = np.array([23, 22, 12])
print(np.concatenate([array_x, array_y]))

# you can also concatenate more than two arrays at once
array_z = np.array([23,45])
print(np.concatenate([array_x, array_y, array_z]))

[11 22 13 23 22 12]
[11 22 13 23 22 12 23 45]


**Concatenate 2D array**

In [41]:
# create a 2D array
my_array = np.array([[1, 2, 3],
                 [4, 5, 6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

**Concatenate along the first axis and second axis**

In [43]:
# by default concatenate() is along 'axis = 0'
print(np.concatenate([my_array, my_array]))

# for second axis - columns, use axis =1
print(np.concatenate([my_array, my_array], axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


**Concatenate 1D and 2D array**

In [44]:
# concatenate the 1D and 2D arrays
# consider a 1D array -- 'array_x'
# consider a 2D array -- 'my_array'
np.concatenate((array_x, my_array), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

<table align="left">
    <tr>
        <td>
            <div align="left">
                <font color="#21618C">
                    <b>Note: One can not concatenate the arrays with different dimensions
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

<a id="splitting"> </a>
### 7. Splitting of Array

Splitting is used to split the array into multiple sub-arrays. It is opposite of concatenation, which is implemented by the functions like split(), hsplit(), and so on.

**array_split():** It is used to split the array into sub-arrays. It takes the integer 'N' as the input for the number of splits, even if 'N' does not divide the array into sub-arrays of equal length.In the example, ee split the array of length 8 into 3 sub-arrays; the function 'array_split()' returns <i>8 % 3 (=2)</i> sub-arrays of size <i>8//3 + 1 (=3)</i> and the rest (i.e. one sub-array) of size <i>8//3 (=2)</i>.<br>

**split():**

**vsplit():**<br>
The vsplit() function is used to split an array into multiple sub-arrays vertically (row-wise).

**hsplit():**<br>
The hsplit() function is used to split an array into multiple sub-arrays horizontally (column-wise).

In [45]:
# given array
array_x = np.arange(8) 

# split 'array_x' into 3 sub-arrays using 'array_split'
np.array_split(array_x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [46]:
# split into sub-arrays
print(np.split(array_x, 2))

# split occurs at 5th and 7th indices
array_y = np.split(array_x,[5,7])
print(array_y)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]
[array([0, 1, 2, 3, 4]), array([5, 6]), array([7])]


In [47]:
# split 'array_x' into 3 sub-arrays
np.split(array_x, 3)

ValueError: array split does not result in an equal division

<table align="left">
    <tr>
        <td>
            <div align="left">
                <font color="#21618C">
                    <b>The split() function does not allow the integer (N) as number of splits, if N does not divide the array into sub-arrays of equal length
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [50]:
my_array = np.arange(20.0).reshape(4,5)
print(my_array)

# split vertically
print(np.vsplit(my_array, 2))

# split horizontally
new_array = np.arange(16.0).reshape(4,4)
print(new_array)
print(np.hsplit(new_array, 2))

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
[array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]]), array([[10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]
